<?= $this->_apilaCss('Cliente/Comun/css/form.css') ?>

<img class="page-font" src="Cliente/Comun/imagenes/background2.png">

<div class="form f-left f-700">
	<div class="f-header f-tag"> Registre sus datos en el sistema</div>
	<div class="body">
		<input class="f-element f-input" id="nombre"
			   value="" type="text" placeholder="Nombre ...">
		<input class="f-element f-input" id="p_apellido"
			   value="" type="text" placeholder="Apellido paterno ...">
		<input class="f-element f-input" id="s_apellido"
			   value="" type="text" placeholder="Apellido materno ...">
		<input class="f-element f-input" id="correo_electronico"
			   value="" type="text" placeholder="Dirección de correo ...">
		<input class="f-element f-input" id="telefono"
			   value="" type="text" placeholder="Número de teléfono ...">
		<input class="f-element f-input" id="usuario"
			   value="" type="text" placeholder="Nombre de usuario ...">
		<input class="f-element f-input" id="clave"
			   value="" type="password" placeholder="Clave ...">
		<button class="f-element f-tag" id="btn-registrar">Registrar</button>
	</div>
</div>